//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess.entits
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskDataTable
    {
        public int taskId { get; set; }
        public string taskName { get; set; }
        public Nullable<int> taskStatus { get; set; }
        public string description { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual statusTable statusTable { get; set; }
        public virtual User User { get; set; }
    }
}
