//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiraDamy.entits
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class taskDataTable
    {
        public int taskId { get; set; }
        
        [Required(ErrorMessage ="please enter task name")]
        public string taskName { get; set; }
        public Nullable<int> taskStatus { get; set; }

        [Required(ErrorMessage = "pleas enter description")]
        public string description { get; set; }
        public virtual statusTable statusTable { get; set; }
    }
}
